_schema:
  content:
    type: String
    required: content must be required
  status:
    type: String
    default: undone
_options:
  timestamps: true

# custom setup used by Auth Plugin (not agradon core)
_auth:
  get: true
  post: true
  put: true
  delete: true
